Create table IF NOT EXISTS megasoft.worker (
ID int AUTO_INCREMENT,
NAME varchar (255) NOT NULL,
BIRTHDAY date,
LEVEL ENUM('Trainee', 'Junior', 'Middle', 'Senior') NOT NULL,
SALARY DECIMAL,
PRIMARY KEY (ID),
CONSTRAINT CHK_W_NAMELEN CHECK (CHAR_LENGTH(NAME) >= 2 AND CHAR_LENGTH(NAME) <= 1000),
CONSTRAINT CHK_BD CHECK (BIRTHDAY > '1900-01-01'),
CONSTRAINT CHK_SAL CHECK (SALARY>=100 AND SALARY<=100000)
);
create table IF NOT EXISTS megasoft.client (
ID int AUTO_INCREMENT,
NAME varchar (255) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT CHK_CL_NAMELEN CHECK (CHAR_LENGTH(NAME) >= 2 AND CHAR_LENGTH(NAME) <= 1000)
);
CREATE table IF NOT EXISTS megasoft.project (
ID int AUTO_INCREMENT,
CLIENT_ID int,
START_DATE date,
FINISH_DATE date,
PRIMARY KEY (ID),
CONSTRAINT CLIENT_ID_FK FOREIGN KEY(CLIENT_ID) REFERENCES megasoft.client(ID)
);
CREATE table IF NOT EXISTS megasoft.project_worker (
PROJECT_ID int,
WORKER_ID int,
PRIMARY KEY (PROJECT_ID, WORKER_ID),
CONSTRAINT PROJECT_ID_FK FOREIGN KEY(PROJECT_ID) REFERENCES megasoft.project(ID),
CONSTRAINT WORKER_ID_FK FOREIGN KEY(WORKER_ID) REFERENCES megasoft.worker(ID)
);
